import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Button, Grid, Typography } from '@mui/material'
import MobileContainer from '../components/mobileContainer/MobileContainer'
import Logo from '../../public/assets/photo/logo/Group.svg'
import GoogleIcon from '../../public/assets/icons/Google-logo.svg'
import AppleIcon from '../../public/assets/icons/Apple-logo.svg'
import { ReactNode } from 'react'

interface signingOptionType {
  id:Number,
  name:String,
  icon:ReactNode
}
export default function Home() {
  const signingOption : signingOptionType[] = [{
    id:0,
    name:'Google',
    icon:<GoogleIcon/>,
  },
  {
    id:1,
    name:'Apple',
    icon:<AppleIcon/>,
  }]
  return (
    <>
      <Head>
        <title>Tasks Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          <MobileContainer>
            <Grid 
            container 
            display={'flex'}
            flexDirection={'column'}
            alignItems={'center'}
            justifyContent={'center'}
            width={'375px'}>
                  <Grid item mt={'97px'}mb={'30px'}>
                    {/* use @svgr/webpack config */}
                    <Logo/>
                    
                      {/* <Image src={'/public/assets/photos/logo/Group.jpg'}
                      alt=''
                      width={113}
                      height={113}/> */}
                  </Grid>
                    <Typography 
                        variant='h3'>
                            My Study Life
                    </Typography>
                    <Typography 
                        color={'grey.100'}
                        textAlign={'center'}
                        fontSize={'1rem'}
                        mx={'40px'}
                        mt={'12px'}>
                            Create a unique emotional story that describes better than words
                    </Typography>
                <Grid
                item
                container
                bgcolor={'#fff'}
                border={'1px solid'}
                borderRadius={'24px'}
                borderColor={'divider'}
                height={'375px'}
                mt={'32px'}
                >
                  <Grid
                  m={'24px'}>
                      <Typography>
                        Signin with
                      </Typography>
                      <Grid>
                        
                        <Button
                          variant='outlined'
                          sx={{
                            width:'152px',
                            height:'64px',
                            color:'grey.300',
                            borderRadius:'12px',
                            padding:'0px',
                            gap:'8px',
                            textTransform:'none'
                          }}>
                              <GoogleIcon/>
                              Google
                        </Button>
                        <Button>Apple</Button>
                      </Grid>
                  </Grid>
                </Grid>
            </Grid>

          </MobileContainer>
      </main>
    </>
  )
}
